
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://mongo_db:27017/song-hub-db
    depends_on:
      - mongo_db

  mongo_db:
    container_name: songhub_database_container
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
